
server:
  port: 9001

spring:
  application:
    name: cloud-order-service #服务名称

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配额ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

ribbon:
  ReadTimeout: 5000 #建立连接所用的时间
  ConnectTimeout: 5000 #建立连接后，服务器读取到资源的可用时间