server:
  port: 9001
spring:
  application:
    name: order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配额ribbon使用负载均衡
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #客户端像服务端发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 2 #服务端在收到最后一次心跳请求后等待时间上线，超时将剔除服务
feign:
  hystrix:
    enabled: true

