
server:
  port: 8001

info:
  app:
    name: payment server
    version: 1.0

spring:
  application:
    name: cloud-payment-service #服务名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hjs.springcloud.entities  #所有entity别名所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配额ribbon使用负载均衡
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #客户端像服务端发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 2 #服务端在收到最后一次心跳请求后等待时间上线，超时将剔除服务
